movie/movieproject/credientials/urls.py
from . import views
from django.urls import path

app_name = 'credientials'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('update/<int:id>/', views.update, name='update'),
]

movie/movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [

    path('',views.allProCat,name='allProCat'),
    path('search/', views.SearchResult, name='SearchResult'),
    path('add/', views.add_movie, name='add_movie'),
    path('<slug:c_slug>/', views.allProCat, name='product_by_category'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('<slug:c_slug>/<slug:movie_slug>/', views.proDetail, name='prodCatdetail'),




]

movie/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
    # path('search/', include('searchapp.urls')),
    path('credientials/',include('credientials.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
           document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

movie/movieproject/templates/add_movie.html

  {% extends 'base.html' %}
{%  load static  %}

{% block metadescription %}

        {{product.description|truncatewords:155}}

        Welcome to GMart store where you can buys different items....

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name}}-GMart store}}

    {% endif %}
{% endblock %}

{% block content %}
 <!-- Single Page Header start -->
        <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Movie</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="{% url 'movieapp:allProCat' %}">Home</a></li>
<!--                <li class="breadcrumb-item"><a href="#">Pages</a></li>-->
<!--                <li class="breadcrumb-item active text-white">Contact</li>-->
            </ol>
        </div>


   <!-- Contact Start -->
        <div class="container-fluid contact py-5">
            <div class="container py-5">
                <div class="p-5 bg-light rounded">
                    <div class="row g-4">
                        <div class="col-12">
                            <div class="text-center mx-auto" style="max-width: 700px;">
                                <h1 class="text-primary">Add Movie</h1>
<!--                                <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>-->
                            </div>
                        </div>

                        <div class="col-lg-8 offset-lg-2">
                         {% if user.is_authenticated %}
                            <form action="" method="post" enctype="multipart/form-data" >
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Movie Name</label>
                                    <input type="hidden" name="move_id" class="w-100 form-control border-0 py-3 mb-4"  placeholder="" value="{{user.id}}">
                                    <input type="text" name="move_name" class="w-100 form-control border-0 py-3 mb-4"  placeholder="">
                                </div>
                                <div class="form-group">
                                    <label>Poster</label>
                                    <input type="file" name="poster" class="w-100 form-control border-0 py-3 mb-4"  placeholder="">
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea class="form-control" name="description" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Release Date</label>
                                     <input type="date" name="release_date" class="w-100 form-control border-0 py-3 mb-4" placeholder="">
                                </div>
                                 <div class="form-group">
                                    <label>Actors Name</label>
                                    <textarea class="form-control" name="actors" rows="3"></textarea>
                                </div>

                               <div class="form-group">
                                <label>Category</label>

                                <select class="w-100 form-control border-0 py-3 mb-4" id="cat" name="mcategory" >
                                    {% for i in cat %}
                                  <option   class="w-100 form-control border-0 py-3 mb-4" value="{{i.id}}">{{i.name}}</option>
                                     {% endfor %}

                                </select>

                               </div>

                                <div class="form-group">
                                    <label>Youtube Trailer Link</label>
                                     <input type="text" name="youtube_link" class="w-100 form-control border-0 py-3 mb-4" placeholder="">
                                </div>

                                <button class="w-100 btn form-control border-secondary py-3 bg-white text-primary " type="submit"> Submit</button>

                            </form>
                           {% endif %}

                            {% for msg in messages %}
                            <h2>{{msg}}</h2>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
{% endblock %}

movie/movieproject/templates/category.html
{% extends 'base.html' %}
{%  load static  %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155}}
    {% else %}
        Movie Website and Recommendation Platform
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}-MovieForMe
    {% else %}
        Movie Website and Recommendation Platform
    {% endif %}
{% endblock %}

{% block content %}

{% if category %}
     <div >
         <div class="row my_row_class">
             <div class="mx_auto">
                  <p><a href="{% url 'movieapp:allProCat' %}">Our Movie Collection</a> </p>
             </div>

         </div>
     </div>
   {% endif %}
<div class="mx_auto">
    {% if category %}
    <img  class="my_image"  src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>



                <div class="p-5 ">
                    <div class="row g-4">
                        <div class="col-12">
                            <div class="text-center mx-auto" style="max-width: 700px;">
                                <h1 class="text-primary">{{category.name}}</h1>
<!--                                <p class="mb-4">{{category.description}}</p>-->
                            </div>
                        </div>
                    </div>
                </div>


   {% else %}
<!-- Hero Start -->
        <div class="container-fluid py-5 mb-5 hero-header">
            <div class="container py-5">
                <div class="row g-5 align-items-center">
                    <div class="col-md-12 col-lg-7">
                        <h4 class="mb-3 text-secondary">The Search is Over</h4>
                        <h1 class="mb-5 display-3 text-primary">The Smart Way To Pick A Movie</h1>
                        <div class="position-relative mx-auto">
                            <input class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill" type="number" placeholder="Search">
                            <button type="submit" class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-100" style="top: 0; right: 25%;">Submit Now</button>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-5">
                        <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active rounded">
                                    <img src="{% static 'img/hero-img-1.png' %}" class="img-fluid w-100 h-100 bg-secondary rounded" alt="First slide">
                                    <a href="#" class="btn px-4 py-2 text-white rounded">Top Box Office</a>
                                </div>
                                <div class="carousel-item rounded">
                                    <img src="{% static 'img/hero-img-2.png' %}" class="img-fluid w-100 h-100 rounded" alt="Second slide">
                                    <a href="#" class="btn px-4 py-2 text-white rounded">New Releases</a>
                                </div>
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselId" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselId" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero End -->
 {% endif %}
        <div class="container-fluid fruite py-5">
            <div class="container py-5">
                <div class="tab-class text-center">
                    <div class="row g-4">
                        <div class="col-lg-4 text-start">
                            <h1>Coming Soon </h1>
                        </div>
                        <div class="col-lg-8 text-end">
                            <ul class="nav nav-pills d-inline-flex text-center mb-5">

                                <li class="nav-item">
                                    <a class="d-flex m-2 py-2 " data-bs-toggle="pill" href="#tab-5">
                                        <span class="text-dark" style="width: 130px;"> </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="tab-content">
                        {% if user.is_authenticated %}
                        <div id="tab-1" class="tab-pane fade show p-0 active">
                            <div class="row g-4">
                                <div class="col-lg-12">
                                    <div class="row g-4">
                                         {% for movie in movies.object_list %}
                                        <div class="col-md-6 col-lg-4 col-xl-3">
                                            <div class="rounded position-relative fruite-item">
                                                <div class="fruite-img">
                                                    <a href="{{movie.get_url}}">  <img src="{{movie.poster.url}}" class="img-fluid w-100 rounded-top" alt=""></a>
                                                </div>
                                                <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{movie.category}}</div>
                                                <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                                    <h4>{{movie.name}}</h4>
                                                       <p>{{movie.release_date}}</p>
<!--                                                    <p>{{movie.description|truncatewords:10}}</p>-->
                                                    <div class=" justify-content-between flex-lg-wrap">
                                                        <p class="text-dark fs-5 fw-bold mb-0"></p>
                                                       <a href="{{movie.get_url}}" class="btn border border-secondary rounded-pill px-3 text-primary">Movie Details</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}


                                    </div>
                                </div>
                            </div>
                        </div>
                        {% else %}

                         <div id="tab-1" class="tab-pane fade show p-0 active">
                            <div class="row g-4">
                                <div class="col-lg-12">
                                    <div class="row g-4">
                                         {% for movie in movies.object_list %}
                                        <div class="col-md-6 col-lg-4 col-xl-3">
                                            <div class="rounded position-relative fruite-item">
                                                <div class="fruite-img">
                                                    <a href="">  <img src="{{movie.poster.url}}" class="img-fluid w-100 rounded-top" alt=""></a>
                                                </div>
                                                <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{movie.category}}</div>
                                                <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                                    <h4>{{movie.name}}</h4>
<!--                                                    <p>{{movie.description|truncatewords:10}}</p>-->
                                                    <div class=" justify-content-between flex-lg-wrap">
                                                        <p class="text-dark fs-5 fw-bold mb-0"></p>
                                                       <a href="{% url 'credientials:register' %}" class="btn border border-secondary rounded-pill px-3 text-primary">Movie Details</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}


                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>

 <div class="mx-auto">
        {% if movies.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in movies.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
     {% endif %}
    </div>
{% endblock %}

movie/movieproject/templates/edit.html
 {% extends 'base.html' %}
{%  load static  %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155}}
    {% else %}
        Movie Website and Recommendation Platform
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}-MovieForMe
    {% else %}
        Movie Website and Recommendation Platform
    {% endif %}
{% endblock %}

{% block content %}



        <div class="container-fluid py-5 mb-5 hero-header">
            <div class="container py-5">
                <div class="row g-5 align-items-center">
                    <div class="col-md-12 col-lg-12">

                        <h1 class="mb-5 display-3 text-primary text-center">Profile</h1>

                    </div>

                </div>
            </div>
        </div>

   <section class="vh-100" style="background-color: #f4f5f7;">
          <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
              <div class="col col-lg-8 mb-4 mb-lg-0">
                <div class="form-group">
                  <form method="POST" >
                    {% csrf_token %}
                     {{form.as_p}}
<!--                        <button type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark" style="z-index: 1;">Submit </button>-->
                             <input type="submit" class="btn btn-primary">

                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>

{% endblock %}

movie/movieproject/templates/movie.html
{% extends 'base.html' %}
{%  load static  %}

{% block metadescription %}

        {{product.description|truncatewords:155}}

        Welcome to GMart store where you can buys different items....

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name}}-GMart store}}

    {% endif %}
{% endblock %}

{% block content %}

       <div class="container-fluid page-header py-5">
            <h1 class="text-center text-white display-6">Movie</h1>
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a href="{% url 'movieapp:allProCat' %}">Home</a></li>
            </ol>
        </div>




        <div class="container-fluid py-5 mt-5">
            <div class="container py-5">
                <div class="row g-4 mb-5">
                    <div class="col-lg-12cd col-xl-12">
                        <div class="row g-4">
                            <div class="col-lg-5">
                                <div class="">
                                    <a href="#">
                                        {% if movie.poster %}
                                        <img src="{{movie.poster.url}}" class="img-fluid rounded" alt="Image">
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-7">
                                <h4 class="fw-bold mb-3">{{movie.name}}</h4>
                                <p class="mb-3">Category: {{movie.category}}</p>
                                <h5 class="fw-bold mb-3">Relasing Date:{{movie.release_date}}</h5>

                                <p class="mb-4">{{movie.description}}</p>

                                <p  class=" mb-4 text-primary">Actors: {{movie.actors}}</p>
                                   {% if user.is_authenticated %}
                                {% if user.id == movie.user_id %}
                                <a href="{% url 'movieapp:update' movie.id %}" class="btn border border-secondary rounded-pill px-3 py-1 mb-4 text-primary">Edit</a>
                                <a href="{% url 'movieapp:delete' movie.id %}" class="btn border border-secondary rounded-pill px-3 py-1 mb-4 text-primary">Delete</a>
                                {% endif %}
                                   {% endif %}
                            </div>
                            <div class="col-lg-12">
                                <nav>
                                    <div class="nav nav-tabs mb-3">
                                        <button class="nav-link active border-white border-bottom-0" type="button" role="tab"
                                            id="nav-about-tab" data-bs-toggle="tab" data-bs-target="#nav-about"
                                            aria-controls="nav-about" aria-selected="true">Trailer</button>
                                        <button class="nav-link border-white border-bottom-0" type="button" role="tab"
                                            id="nav-mission-tab" data-bs-toggle="tab" data-bs-target="#nav-mission"
                                                aria-controls="nav-mission" aria-selected="false">Reviews </button>
                                    </div>
                                </nav>
                                <div class="tab-content mb-5">
                                    <div class="tab-pane active" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">

                                     <a href="{{movie.youtube_link}}" class="btn border border-secondary rounded-pill px-3 py-1 mb-4 text-primary" target="_blank">Watch Video</a>     </p>

                                    </div>

                                    <div class="tab-pane" id="nav-mission" role="tabpanel" aria-labelledby="nav-mission-tab">
                                         {% for x in reviews %}
                                        <div class="d-flex">
                                            <img src="{% static 'img/avatar.jpg' %}" class="img-fluid rounded-circle p-3" style="width: 100px; height: 100px;" alt="">
                                            <div class="">

                                                            <p>{{ x.review_desp }}</p>

                                                                {% if x.rating > 0 %}
                                                                  <i class="fa fa-star {% if x.rating  < 1 %} no-checked {% else %} checked {% endif %} " id="check-star"></i>
                                                                  <i class="fa fa-star {% if x.rating  < 2 %} no-checked {% else %} checked {% endif %} " id="check-star"></i>
                                                                  <i class="fa fa-star {% if x.rating  < 3 %} no-checked {% else %} checked {% endif %} " id="check-star"></i>
                                                                  <i class="fa fa-star {% if x.rating  < 4 %} no-checked {% else %} checked {% endif %} " id="check-star"></i>
                                                                  <i class="fa fa-star {% if x.rating  < 5 %} no-checked {% else %} checked {% endif %} " id="check-star"></i>
                                                                <hr>
                                                                {% else %}

                                                                     <i class="fa fa-star " id="star"></i>
                                                                     <i class="fa fa-star" id="star"></i>
                                                                     <i class="fa fa-star" id="star"></i>
                                                                     <i class="fa fa-star" id="star"></i>
                                                                     <i class="fa fa-star" id="star"></i>
                                                                            &nbsp;<span>No ratings</span>

                                                                    <hr>

                                                                 {% endif %}


                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>

                                </div>
                            </div>

                            <form action="#" method="Post">
                                 {% csrf_token %}
                                <h4 class="mb-5 fw-bold">Leave a Reply</h4>
                                <div class="row g-4">

                                    <div class="col-lg-12">
                                        <div class="border-bottom rounded my-4">
                                            <textarea name="item_review" id="review-text" class="form-control border-0" cols="30" rows="8" placeholder="Your Review *" spellcheck="false"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="d-flex justify-content-between py-3 mb-5">
                                            <div class="d-flex align-items-center">

                                                <div class="rating">

                                                  <input type="radio" id="star5" name="rating" value="5" />
                                                  <label class="star" for="star5" title="Awesome" aria-hidden="true"></label>
                                                  <input type="radio" id="star4" name="rating" value="4" />
                                                  <label class="star" for="star4" title="Great" aria-hidden="true"></label>
                                                  <input type="radio" id="star3" name="rating" value="3" />
                                                  <label class="star" for="star3" title="Very good" aria-hidden="true"></label>
                                                  <input type="radio" id="star2" name="rating" value="2" />
                                                  <label class="star" for="star2" title="Good" aria-hidden="true"></label>
                                                  <input type="radio" id="star1" name="rating" value="1" />
                                                  <label class="star" for="star1" title="Bad" aria-hidden="true"></label>

                                                </div>
                                            </div>
                                            <div class="row">

                                                <div class="col-md-4">
                                                    <input type="submit"  class="btn btn-primary mt-2" value="Post Comment">



                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>


                        </div>
                    </div>

                </div>

                </div>
            </div>
        </div>

{% endblock %}

movie/movieproject/templates/navbar.html
{% load static %}
<!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container topbar bg-primary d-none d-lg-block">
                <div class="d-flex justify-content-between">
                    <div class="top-info ps-2">
                        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">123 Street, New York</a></small>
                        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
                    </div>
                    <div class="top-link pe-2">

                    </div>
                </div>
            </div>
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a href="index.html" class="navbar-brand"><img src="{% static 'img/logo.png' %}"></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a href="{% url 'movieapp:allProCat' %}" class="nav-item nav-link active">Home

                                {% if user.is_authenticated %}

                                <a href="{% url 'movieapp:add_movie' %}" class="nav-item nav-link">Add Movie</a>

                                <div class="nav-item dropdown">
                                <a href="" class="nav-link dropdown-toggle {% if 'movieapp' in request.path %} active {% endif %}" data-bs-toggle="dropdown">Top Genres</a>

                                  <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                      <a href="{% url 'movieapp:allProCat' %}" class="dropdown-item">All Movies</a>
                                      {% for cat in links %}
                                    <a href="{{cat.get_url}}" class="dropdown-item">{{cat.name}}</a>
                                        {% endfor %}
                                  </div>

                                </div>
                                <a href="{% url 'credientials:logout' %}" class="nav-item nav-link">Logout</a>

                                {% else %}
                                <a href="{% url 'credientials:register' %}" class="nav-item nav-link">Register</a>
                                <a href="{% url 'credientials:login' %}" class="nav-item nav-link">Login</a>
                                {% endif %}
                        </div>

                                {% if user.is_authenticated %}
                                 <form class="d-flex" role="search" action="{% url 'movieapp:SearchResult' %}" method="get">
                                    {% csrf_token %}
                                    <input class="form-control me-2"  name="q" type="search" placeholder="Search" aria-label="Search">
                                    <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                                 </form>


                                <div class="d-flex m-3 me-0">
                                    <a href="{% url 'credientials:profile' user.id %}" class="my-auto">
                                        <i class="fas fa-user fa-2x"></i>&nbsp;&nbsp;{{user.username}}
                                    </a>
                                </div>
                                {% endif %}


                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->
